# Generated by Django 2.1.1 on 2018-09-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Product_idx', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('facebook_addr', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('member_num', models.IntegerField()),
                ('notice', models.TextField(blank=True)),
                ('site_name', models.CharField(max_length=128)),
                ('img_path', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('direct', models.IntegerField()),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroNine.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_has_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.IntegerField()),
                ('order_option', models.CharField(max_length=64)),
                ('product_url', models.CharField(max_length=64)),
                ('Product_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroNine.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('student_num', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='product_has_user',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeroNine.User'),
        ),
    ]
